### ISSUE TITLE
Grouped selectors not compiled properly in segments

### ISSUE THREAD

**Issue by clintjhill** [bkardell/Hitch#10]
Example rule:
div:myplugin-below(20), p:myplugin-below(20) { color: green; }

Result:
div:myplugin-below(20), p:-webkit-any([below])._2

Is this expected result for a segment selector?

**Comment by bkardell** [comment]
No.  I will try to verify this with my code, but that seems wrong.  Do you have any more info?  Is the problem limited to reuse of the same filter in the same selector or anything?  

We need qunit.

That selector could be written:

:-plugins-any(div,p):-myplugin-below(20)

**Comment by clintjhill** [comment]
I added support for grouped and filtered selectors. Needs a quick review though.

**Comment by bkardell** [comment]
reviewed, expanded a bit, merged into master
